[phases.setup]
nixPkgs = ['python39', 'gcc', 'pkg-config']
aptPkgs = ['libpq-dev']

[phases.install] 
cmds = [
  'cd backend',
  'pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[phases.build]
cmds = [
  'cd backend',
  'python manage.py collectstatic --noinput --clear',
  'python manage.py migrate --run-syncdb'
]

[start]
cmd = 'cd backend && gunicorn --bind 0.0.0.0:$PORT --timeout 120 eeg_backend.wsgi:application'